default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/tenant.sqlite3
    migrations_paths: db/migrate_tenant

# rails db:migrate:primary
    
  shared:
    <<: *default
    database: storage/shared.sqlite3
    migrations_paths: db/migrate_shared

# For the shared database to create a migration file run the following
# rails generate migration CreateFoo --database=shared
#
# rails db:migrate:shared
